### ISSUE TITLE
您是否可以增加全角字符转化为半角字符的功能。

### ISSUE THREAD

**Issue by CplusBest** [moshuying/myAHK#3]
在某下情况下，输入【和[我都想得到[],我自己尝试了很多次但都失败了。

**Comment by moshuying** [comment]
很抱歉之前没有收到issues的通知，这个问题其实是之前有的一个功能它可以通过按下caps+9开启全半角或中英文都输入英文代码符号（后来在用的过程中发现在很多通用场景中使用并不是很方便于是砍掉了），可能近期会做成通过呼出GUI控制面板和快捷键两种方式来开启和关闭不常用的功能，由于近期的工作重心不在myAHK上，这部分功能的开发可能暂时会被延后。

**Comment by moshuying** [comment]
抱歉，这个功能我暂时没有想到合适的方法来做，全半角符号输入方式比较多样，可以做到的是由键盘输入的字符做全半角转换。如果您喜欢这个功能，可以为您打包一版支持开启和关闭按`shift`+1~0，以及其他字符的全半角转换。
